name: "Continuous Integration"

on: [ push ]

jobs:
    quality:
        name: Quality
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v1
            -   name: Install PHP extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1.2'
                    tools: pecl, composer, flex, cs2pr, php-cs-fixer, phpmd, phpcpd, phpstan
                    ini-values: memory_limit=-1
                    extensions: xsl, zip, ctype, json
            -   name: Cache Composer packages
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache
                    key: composer-${{ github.sha }}
                    restore-keys: composer-
                continue-on-error: true
            -   name: Install project dependencies
                run: composer install --no-progress --no-suggest --ansi
            -   name: Run prepare PHPUnit
                run: mkdir -p build/logs
            -   name: Run PHPUnit units tests
                run: vendor/bin/phpunit --testdox
            -   name: Run PHPMD
                run: phpmd src text .phpmd.xml
            -   name: Run PHPCPD
                run: phpcpd src
            -   name: Run PHP-CS-Fixer fix
                run: php-cs-fixer fix --dry-run --diff --using-cache=no --ansi --format=checkstyle | cs2pr
            -   name: Run PHPStan analysis
                run: phpstan analyse --memory-limit=4G -l 8 src --error-format=checkstyle | cs2pr
            -   name: Upload artifacts
                if: always()
                uses: actions/upload-artifact@v1
                with:
                    name: phpunit-logs
                    path: build/logs
                continue-on-error: true
